### ISSUE TITLE
Screen size problem

### ISSUE THREAD

**Issue by OrozcoMon** [maruohon/malilib#170]
I have a GUI problem where i can't see the configs and that affects other mods that need malilib. I updated yesterday to 1.21.3 and it was when the problem started, while i was playing in 1.21.1 everything worked fine. Also the mod is in Spanish and i would like to have it in English, is there any way to fix it?
![imagen_2024-12-04_211028194](https://github.com/user-attachments/assets/189572cb-99b4-480d-b0ca-ad6c95a313d0)

**Comment by maruohon** [comment]
The GUI scale is based on the vanilla GUI scale setting. So currently you would need to change that to change the mod GUI scale too. (The main development code in 1.12.2 has a separate GUI scale config for the malilib-based screens... so that should come *at some point* to the other MC versions too.)

The mod follows the game localization setting, if there are translations available for it. I guess currently the only way to have it not do that would be to delete the corresponding lang file from the mod jar. (You can open the jar file with 7-zip or WinRAR etc (it's basically a zip file) and just delete the lang file from the `assets/<modid>/lang/` directory in there.)

**Comment by OrozcoMon** [comment]
Thanks for the fast answer! I will be waiting for the GUI scale, and thank you so much about the language problem. Hope you have a good day! ^^
