### ISSUE TITLE
Curseforge not showing versions. force installing Rift and not enabling version control to change to fabric version.

### ISSUE THREAD

**Issue by usafphoenix** [maruohon/malilib#51]
Installing tweakeroo to a fabric modpack force-installs incorrect RIFT version of mod; curseforge does not show other versions of malalib, or perform a search for the mod correctly. can't install correct version. screenshot provided for review. 

https://ibb.co/jy7YMmD

image will autodelete 8/8/2021.

**Comment by maruohon** [comment]
Well that just makes no sense at all... All of the files should be correctly marked for the mod loader they are made for. There isn't anything else I can do AFAIK. Maybe it's a temporary bug of some kind in the overwolf app whatever it is these days?

![image](https://user-images.githubusercontent.com/2331050/124956951-3a349800-e021-11eb-9473-429a1af0aed2.png)

![image](https://user-images.githubusercontent.com/2331050/124957016-4a4c7780-e021-11eb-8858-7e33c3fe0711.png)

**Comment by usafphoenix** [comment]
Yeah, curseforge/overwolf has been a major pain since...well...forever.
Essentially the fix for these things tends to be:
1) delete the offending file
2) open chrome and download it manually
3) move file into mods folder manually
4) pray.

But it's something I like to make authors aware of (eventhough i'm pretty sure it's actually a problem on overwolf's side). mod authors can at least put a note on their mod page saying "overwolf sucks and here's how to fix this if it happens to you" lol.

**Comment by maruohon** [comment]
Can you share any additional details about this issue? I opened a support ticket at Overwolf, but the support person couldn't reproduce this on 1.16.5 or 1.17.

Personally I haven't used the app/launcher since the early Curse launcher a few years back, so I don't know anything about it. Ie. stuff like how do you define the MC version and mod loader for the profile/pack/whatever, were those set correctly? Was the problem just for malilib, and do for example my other mods that depend on malilib get installed in the correct versions? (Item Scroller, Litematica, MiniHUD, Tweakeroo). And do they correctly list all the other available mod versions for the MC version in question? ie. does it show all the versions that you can see if you go to the CurseForge web site and look on the Files page. Does malilib get automatically pulled in by the app, or did you install it manually? Does it work if you remove all the related mods and then first install malilib yourself via the app, instead of it getting pulled in as a dependency?

**Comment by usafphoenix** [comment]
I don't know what to share on it, other than I was creating a minecraft
modpack for 1.17.1 with fabric and using the built in "add more content"
and the version it installed from there was the rift one, and then
complained @ me cause it was obviously not the right file. Manually
deleting it and installing from a downloads folder fixes this. Not sure why
it installed the rift version.
