### ISSUE TITLE
malilib 0.10.0-dev.21+beta.1 forge does not exist for download

### ISSUE THREAD

**Issue by grabielkz** [maruohon/malilib#60]
I was looking for malilib 0.10.0-dev.21+beta.1 (forge) and it was not downloadable from CurseForge, please add to download

**Comment by maruohon** [comment]
Those current 1.16.5 Forge versions of malilib and Litematica are not ported by me, so I will not upload those to CurseForge. I haven't checked the code in those versions that everything works as it's supposed to and is ported correctly (and in fact I know that at least the hotkey config changes are not applied when you close the config menu - you have to log out of the world and back in for the hotkey changes to get applied), so those versions are not "officially supported" by me, although I still end up doing some user support for them anyway...

Proper full Forge ports are only going to be made from the new, largely rewritten code of all the mods that I'm currently working on. And I have no idea how long all of it is still going to take. Progress has been really slow lately, due to all kinds of other distractions...
